[workspace]
members = [
  "crates/bingo-abi",
  "crates/bingo-memory",
  "crates/bingo-runtime",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.97"
version = "0.1.0"

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = false
opt-level = 2
panic = "abort"
strip = "debuginfo"
