#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schema" / "abi-v1.json"


def load_schema():
    with SCHEMA_PATH.open(encoding="utf-8") as stream:
        schema = json.load(stream)
    if set(schema) != {"schemaVersion", "runtimeABIVersion", "functions"}:
        raise SystemExit("ABI schema has unexpected fields")
    if schema["schemaVersion"] != 1 or schema["runtimeABIVersion"] != 1:
        raise SystemExit("unsupported ABI schema version")
    names = [function["name"] for function in schema["functions"]]
    if len(names) != len(set(names)):
        raise SystemExit("ABI schema contains duplicate function names")
    return schema


def rust_abi(schema):
    return (
        "// Code generated by tools/generate_abi.py; DO NOT EDIT.\n\n"
        f"pub const ABI_SCHEMA_VERSION: u32 = {schema['schemaVersion']};\n"
        f"pub const RUNTIME_ABI_VERSION: u32 = {schema['runtimeABIVersion']};\n"
    )


def rust_exports(schema):
    lines = ["// Code generated by tools/generate_abi.py; DO NOT EDIT.", ""]
    for function in schema["functions"]:
        if function["implementation"] != "runtime":
            continue
        if function["returnType"] != "u32" or not function.get("worker"):
            raise SystemExit(f"unsupported runtime export: {function}")
        lines.extend(
            [
                "#[unsafe(no_mangle)]",
                f"pub extern \"C\" fn {function['name']}() -> u32 {{",
                f"    crate::{function['worker']}()",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def c_header(schema):
    c_types = {"u32": "uint32_t", "void": "void"}
    lines = [
        "/* Code generated by tools/generate_abi.py; DO NOT EDIT. */",
        "#ifndef BINGO_ABI_H",
        "#define BINGO_ABI_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define BINGO_ABI_SCHEMA_VERSION {schema['schemaVersion']}u",
        f"#define BINGO_RUNTIME_ABI_VERSION {schema['runtimeABIVersion']}u",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    for function in schema["functions"]:
        try:
            result = c_types[function["returnType"]]
        except KeyError as error:
            raise SystemExit(f"unsupported C ABI type: {error.args[0]}") from error
        lines.append(f"{result} {function['name']}(void);")
    lines.extend(["", "#ifdef __cplusplus", "}", "#endif", "", "#endif", ""])
    return "\n".join(lines)


def outputs(schema):
    return {
        ROOT / "crates" / "bingo-abi" / "src" / "generated.rs": rust_abi(schema),
        ROOT / "crates" / "bingo-runtime" / "src" / "generated_exports.rs": rust_exports(schema),
        ROOT / "include" / "bingo_abi.h": c_header(schema),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    mismatches = []
    for path, content in outputs(load_schema()).items():
        if arguments.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                mismatches.append(path.relative_to(ROOT).as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    if mismatches:
        raise SystemExit("generated ABI files are stale: " + ", ".join(mismatches))


if __name__ == "__main__":
    main()
