#!/usr/bin/env python3
import argparse
import hashlib
import json
import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schema" / "abi-v1.json"
OBJECT_LAYOUT_SCHEMA_PATH = ROOT / "schema" / "object-layout-v1.json"


def load_schema():
    with SCHEMA_PATH.open(encoding="utf-8") as stream:
        schema = json.load(stream)
    if set(schema) != {"schemaVersion", "runtimeABIVersion", "structs", "functions"}:
        raise SystemExit("ABI schema has unexpected fields")
    if schema["schemaVersion"] != 1 or schema["runtimeABIVersion"] != 1:
        raise SystemExit("unsupported ABI schema version")
    names = [function["name"] for function in schema["functions"]]
    if len(names) != len(set(names)):
        raise SystemExit("ABI schema contains duplicate function names")
    for function in schema["functions"]:
        if set(function) not in (
            {"name", "returnType", "parameters", "implementation"},
            {"name", "returnType", "parameters", "implementation", "worker"},
        ):
            raise SystemExit(f"ABI function has unexpected fields: {function}")
        if function["implementation"] not in {"runtime", "startup", "program"}:
            raise SystemExit(f"unsupported ABI implementation: {function}")
        parameter_names = [parameter["name"] for parameter in function["parameters"]]
        if len(parameter_names) != len(set(parameter_names)):
            raise SystemExit(f"ABI function has duplicate parameter names: {function}")
    struct_names = [value["name"] for value in schema["structs"]]
    if len(struct_names) != len(set(struct_names)):
        raise SystemExit("ABI schema contains duplicate struct names")
    abi_field_types = {"frame_ptr", "object_slots_ptr", "u16_ptr", "u32", "u64", "usize"}
    for value in schema["structs"]:
        if set(value) != {"name", "fields"}:
            raise SystemExit(f"ABI struct has unexpected fields: {value}")
        field_names = [field["name"] for field in value["fields"]]
        if len(field_names) != len(set(field_names)):
            raise SystemExit(f"ABI struct has duplicate fields: {value['name']}")
        for field in value["fields"]:
            if set(field) != {"name", "type"} or field["type"] not in abi_field_types:
                raise SystemExit(f"unsupported ABI struct field: {field}")
    return schema


def load_object_layout_schema():
    with OBJECT_LAYOUT_SCHEMA_PATH.open(encoding="utf-8") as stream:
        schema = json.load(stream)
    if set(schema) != {"schemaVersion", "structs"} or schema["schemaVersion"] != 1:
        raise SystemExit("unsupported object layout schema")
    names = [value["name"] for value in schema["structs"]]
    if len(names) != len(set(names)):
        raise SystemExit("object layout schema contains duplicate struct names")
    for value in schema["structs"]:
        if set(value) != {"name", "fields"}:
            raise SystemExit(f"object layout struct has unexpected fields: {value}")
        field_names = [field["name"] for field in value["fields"]]
        if len(field_names) != len(set(field_names)):
            raise SystemExit(f"object layout struct has duplicate fields: {value['name']}")
        for field in value["fields"]:
            if set(field) != {"name", "type"} or field["type"] not in {"ptr", "usize", "u8", "u16", "u32"}:
                raise SystemExit(f"unsupported object layout field: {field}")
    return schema


def object_layout_schema_hash(schema):
    canonical = json.dumps(schema, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("ascii")
    return hashlib.sha256(canonical).hexdigest()


def rust_abi(schema, object_layout):
    lines = [
        "// Code generated by tools/generate_abi.py; DO NOT EDIT.\n\n"
        f"pub const ABI_SCHEMA_VERSION: u32 = {schema['schemaVersion']};\n"
        f"pub const RUNTIME_ABI_VERSION: u32 = {schema['runtimeABIVersion']};\n"
        f"pub const OBJECT_LAYOUT_SCHEMA_VERSION: u32 = {object_layout['schemaVersion']};\n"
        "pub const OBJECT_LAYOUT_SCHEMA_HASH: &str =\n"
        f"    \"{object_layout_schema_hash(object_layout)}\";\n"
        "pub const BINGO_GC_OK: u32 = 0;\n"
        "pub const BINGO_GC_INVALID_ARGUMENT: u32 = 1;\n"
        "pub const BINGO_GC_WRONG_THREAD: u32 = 2;\n"
        "pub const BINGO_GC_OUT_OF_MEMORY: u32 = 3;\n"
        "pub const BINGO_GC_CORRUPT_HEAP: u32 = 4;\n"
        "pub const BINGO_GC_FRAME_STATE: u32 = 5;\n"
        "pub const BINGO_DYNAMIC_EXCEPTION: u32 = 6;\n"
    ]
    rust_types = {"ptr": "*const core::ffi::c_void", "usize": "usize", "u8": "u8", "u16": "u16", "u32": "u32"}
    for value in object_layout["structs"]:
        lines.extend(["\n#[repr(C)]\n", f"pub struct {value['name']} {{\n"])
        for field in value["fields"]:
            lines.append(f"    pub {field['name']}: {rust_types[field['type']]},\n")
        lines.append("}\n")
    rust_abi_types = {
        "frame_ptr": "*mut BingoGcFrameV1",
        "object_slots_ptr": "*mut *mut BingoObjectHeaderV1",
        "u16_ptr": "*const u16",
        "u32": "u32",
        "u64": "u64",
        "usize": "usize",
    }
    for value in schema["structs"]:
        lines.extend(["\n#[repr(C)]\n", f"pub struct {value['name']} {{\n"])
        for field in value["fields"]:
            lines.append(f"    pub {field['name']}: {rust_abi_types[field['type']]},\n")
        lines.append("}\n")
    return "".join(lines)


def rust_exports(schema):
    lines = ["// Code generated by tools/generate_abi.py; DO NOT EDIT.", ""]
    rust_types = {
        "u32": "u32",
        "u64": "u64",
        "shape_ptr": "*const bingo_abi::BingoShapeDescriptorV1",
        "object_ptr": "*mut bingo_abi::BingoObjectHeaderV1",
        "u8_ptr": "*mut u8",
        "object_out": "*mut *mut bingo_abi::BingoObjectHeaderV1",
        "frame_ptr": "*mut bingo_abi::BingoGcFrameV1",
        "stats_ptr": "*mut bingo_abi::BingoGcStatsV1",
        "dynamic_value": "bingo_abi::BingoDynamicValueV1",
        "utf16_view": "bingo_abi::BingoUtf16ViewV1",
        "dynamic_value_out": "*mut bingo_abi::BingoDynamicValueV1",
        "host_number_properties_ptr": "*const bingo_abi::BingoHostNumberPropertyV1",
    }
    for function in schema["functions"]:
        if function["implementation"] != "runtime":
            continue
        if function["returnType"] != "u32" or not function.get("worker"):
            raise SystemExit(f"unsupported runtime export: {function}")
        try:
            parameters = [f"{value['name']}: {rust_types[value['type']]}" for value in function["parameters"]]
        except KeyError as error:
            raise SystemExit(f"unsupported Rust ABI type: {error.args[0]}") from error
        arguments = ", ".join(value["name"] for value in function["parameters"])
        signature = f"pub extern \"C\" fn {function['name']}({', '.join(parameters)}) -> u32 {{"
        if len(signature) > 100:
            signature_lines = [f"pub extern \"C\" fn {function['name']}("]
            signature_lines.extend(f"    {parameter}," for parameter in parameters)
            signature_lines.append(") -> u32 {")
        else:
            signature_lines = [signature]
        lines.extend(
            [
                "#[unsafe(no_mangle)]",
                *signature_lines,
                f"    crate::{function['worker']}({arguments})",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def c_header(schema, object_layout):
    c_types = {
        "u8": "uint8_t", "u32": "uint32_t", "u64": "uint64_t", "void": "void", "f64": "double",
        "nullable_f64": "BingoNullableNumber", "utf16_string": "BingoUtf16String",
        "shape_ptr": "const BingoShapeDescriptorV1 *", "object_ptr": "BingoObjectHeaderV1 *",
        "u8_ptr": "uint8_t *",
        "object_out": "BingoObjectHeaderV1 **", "frame_ptr": "BingoGcFrameV1 *",
        "stats_ptr": "BingoGcStatsV1 *",
        "dynamic_value": "BingoDynamicValueV1",
        "utf16_view": "BingoUtf16ViewV1",
        "dynamic_value_out": "BingoDynamicValueV1 *",
        "host_number_properties_ptr": "const BingoHostNumberPropertyV1 *",
    }
    lines = [
        "/* Code generated by tools/generate_abi.py; DO NOT EDIT. */",
        "#ifndef BINGO_ABI_H",
        "#define BINGO_ABI_H",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "typedef struct BingoNullableNumber {",
        "    uint8_t tag;",
        "    uint8_t reserved[7];",
        "    double payload;",
        "} BingoNullableNumber;",
        "",
        "typedef struct BingoUtf16String {",
        "    const uint16_t *data;",
        "    uint64_t length;",
        "} BingoUtf16String;",
        "",
    ]
    c_layout_types = {"ptr": "const void *", "usize": "size_t", "u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t"}
    for value in object_layout["structs"]:
        lines.append(f"typedef struct {value['name']} {{")
        for field in value["fields"]:
            lines.append(f"    {c_layout_types[field['type']]} {field['name']};")
        lines.extend([f"}} {value['name']};", ""])
    c_abi_types = {
        "frame_ptr": "struct BingoGcFrameV1 *",
        "object_slots_ptr": "BingoObjectHeaderV1 **",
        "u16_ptr": "const uint16_t *",
        "u32": "uint32_t",
        "u64": "uint64_t",
        "usize": "size_t",
    }
    for value in schema["structs"]:
        lines.append(f"typedef struct {value['name']} {{")
        for field in value["fields"]:
            lines.append(f"    {c_abi_types[field['type']]} {field['name']};")
        lines.extend([f"}} {value['name']};", ""])
    lines.extend([
        f"#define BINGO_ABI_SCHEMA_VERSION {schema['schemaVersion']}u",
        f"#define BINGO_RUNTIME_ABI_VERSION {schema['runtimeABIVersion']}u",
        f"#define BINGO_OBJECT_LAYOUT_SCHEMA_VERSION {object_layout['schemaVersion']}u",
        f"#define BINGO_OBJECT_LAYOUT_SCHEMA_HASH \"{object_layout_schema_hash(object_layout)}\"",
        "#define BINGO_GC_OK 0u",
        "#define BINGO_GC_INVALID_ARGUMENT 1u",
        "#define BINGO_GC_WRONG_THREAD 2u",
        "#define BINGO_GC_OUT_OF_MEMORY 3u",
        "#define BINGO_GC_CORRUPT_HEAP 4u",
        "#define BINGO_GC_FRAME_STATE 5u",
        "#define BINGO_DYNAMIC_EXCEPTION 6u",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ])
    for function in schema["functions"]:
        try:
            result = c_types[function["returnType"]]
        except KeyError as error:
            raise SystemExit(f"unsupported C ABI type: {error.args[0]}") from error
        parameters = []
        for parameter in function["parameters"]:
            try:
                parameter_type = c_types[parameter["type"]]
            except KeyError as error:
                raise SystemExit(f"unsupported C ABI type: {error.args[0]}") from error
            parameters.append(f"{parameter_type} {parameter['name']}")
        lines.append(f"{result} {function['name']}({', '.join(parameters) if parameters else 'void'});")
    lines.extend(["", "#ifdef __cplusplus", "}", "#endif", "", "#endif", ""])
    return "\n".join(lines)


def go_object_layout_schema(object_layout):
    return (
        "// Code generated by runtime/bingo-rt/tools/generate_abi.py; DO NOT EDIT.\n\n"
        "package bingo\n\n"
        f"const ObjectLayoutABISchemaHash = \"{object_layout_schema_hash(object_layout)}\"\n"
    )


def outputs(schema, object_layout):
    return {
        ROOT / "crates" / "bingo-abi" / "src" / "generated.rs": rust_abi(schema, object_layout),
        ROOT / "crates" / "bingo-runtime" / "src" / "generated_exports.rs": rust_exports(schema),
        ROOT / "include" / "bingo_abi.h": c_header(schema, object_layout),
        ROOT.parents[1] / "typescript-go" / "internal" / "bingo" / "object_layout_schema_generated.go": go_object_layout_schema(object_layout),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    mismatches = []
    for path, content in outputs(load_schema(), load_object_layout_schema()).items():
        if arguments.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                mismatches.append(Path(os.path.relpath(path, ROOT)).as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    if mismatches:
        raise SystemExit("generated ABI files are stale: " + ", ".join(mismatches))


if __name__ == "__main__":
    main()
