/* Code generated by tools/generate_abi.py; DO NOT EDIT. */
#ifndef BINGO_ABI_H
#define BINGO_ABI_H

#include <stdint.h>

#define BINGO_ABI_SCHEMA_VERSION 1u
#define BINGO_RUNTIME_ABI_VERSION 1u

#ifdef __cplusplus
extern "C" {
#endif

uint32_t bingo_rt_abi_version_v1(void);
void bingo_startup_empty_v1(void);
double add(double left, double right);
double choose(uint8_t flag, double left, double right);

#ifdef __cplusplus
}
#endif

#endif
