#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
TARGET="${1:-$ROOT/target/first-slice}"
TRIPLE=x86_64-unknown-linux-gnu
CLANG="${CLANG:-clang-20}"

python3 "$ROOT/tools/generate_abi.py" --check
cargo build --manifest-path "$ROOT/Cargo.toml" --workspace --release --locked --target "$TRIPLE" --target-dir "$TARGET/cargo"

ARCHIVE="$TARGET/cargo/$TRIPLE/release/libbingo_runtime.a"
STARTUP="$TARGET/bingo_startup_empty.o"
APPLICATION_STARTUP="$TARGET/bingo_application_startup.o"
HARNESS="$TARGET/bingo_add_harness.o"
COMPUTE_HARNESS="$TARGET/bingo_compute_harness.o"
CHOOSE_HARNESS="$TARGET/bingo_choose_harness.o"
CLASSIFY_HARNESS="$TARGET/bingo_classify_harness.o"
COALESCE_HARNESS="$TARGET/bingo_coalesce_harness.o"
COALESCE_ASSIGN_HARNESS="$TARGET/bingo_coalesce_assign_harness.o"
STRING_LENGTH_HARNESS="$TARGET/bingo_string_length_harness.o"
OBJECT_ALIAS_HARNESS="$TARGET/bingo_object_alias_harness.o"
PROPERTY_NULLISH_ASSIGN_HARNESS="$TARGET/bingo_property_nullish_assign_harness.o"
CLOSURE_COUNTER_HARNESS="$TARGET/bingo_closure_counter_harness.o"
CLASS_COUNTER_HARNESS="$TARGET/bingo_class_counter_harness.o"
DERIVED_COUNTER_HARNESS="$TARGET/bingo_derived_counter_harness.o"
CLASS_ACCESS_HARNESS="$TARGET/bingo_class_access_harness.o"
CHECKED_OBJECT_CAST_HARNESS="$TARGET/bingo_checked_object_cast_harness.o"
MANIFEST="$TARGET/runtime-manifest.json"
INTEROP_MANIFEST="$TARGET/runtime-manifest-interop.json"
SMOKE="$TARGET/runtime-link-smoke"
GC_SMOKE="$TARGET/gc-heap-abi-smoke"
DYNAMIC_PROPERTY_SMOKE="$TARGET/dynamic-property-abi-smoke"

"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/startup/empty.c" -o "$STARTUP"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/startup/application.c" -o "$APPLICATION_STARTUP"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/add_bits.c" -o "$HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/compute_bits.c" -o "$COMPUTE_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/choose_bits.c" -o "$CHOOSE_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/classify_bits.c" -o "$CLASSIFY_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/coalesce_bits.c" -o "$COALESCE_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -DBINGO_COALESCE_ENTRYPOINT=coalesceAssign -c "$ROOT/harness/coalesce_bits.c" -o "$COALESCE_ASSIGN_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/string_length_bits.c" -o "$STRING_LENGTH_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/object_alias_bits.c" -o "$OBJECT_ALIAS_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/property_nullish_assign_bits.c" -o "$PROPERTY_NULLISH_ASSIGN_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/closure_counter_bits.c" -o "$CLOSURE_COUNTER_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/class_counter_bits.c" -o "$CLASS_COUNTER_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/derived_counter_bits.c" -o "$DERIVED_COUNTER_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/class_access_bits.c" -o "$CLASS_ACCESS_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" -c "$ROOT/harness/checked_object_cast_bits.c" -o "$CHECKED_OBJECT_CAST_HARNESS"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" "$ROOT/tests/link_smoke.c" "$STARTUP" "$ARCHIVE" -ldl -lpthread -lm -o "$SMOKE"
"$SMOKE"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" "$ROOT/tests/gc_heap_abi.c" "$ARCHIVE" -ldl -lpthread -lm -o "$GC_SMOKE"
"$GC_SMOKE"
"$CLANG" -target "$TRIPLE" -I"$ROOT/include" "$ROOT/tests/dynamic_property_abi.c" "$ARCHIVE" -ldl -lpthread -lm -o "$DYNAMIC_PROPERTY_SMOKE"
"$DYNAMIC_PROPERTY_SMOKE"
MANIFEST_ARGUMENTS=(--clang "$CLANG" --archive "$ARCHIVE" --startup "$STARTUP" --application-startup "$APPLICATION_STARTUP" --harness "$HARNESS" --compute-harness "$COMPUTE_HARNESS" --choose-harness "$CHOOSE_HARNESS" --classify-harness "$CLASSIFY_HARNESS" --coalesce-harness "$COALESCE_HARNESS" --coalesce-assign-harness "$COALESCE_ASSIGN_HARNESS" --string-length-harness "$STRING_LENGTH_HARNESS" --object-alias-harness "$OBJECT_ALIAS_HARNESS" --property-nullish-assign-harness "$PROPERTY_NULLISH_ASSIGN_HARNESS" --closure-counter-harness "$CLOSURE_COUNTER_HARNESS" --class-counter-harness "$CLASS_COUNTER_HARNESS" --derived-counter-harness "$DERIVED_COUNTER_HARNESS" --class-access-harness "$CLASS_ACCESS_HARNESS" --checked-object-cast-harness "$CHECKED_OBJECT_CAST_HARNESS")
python3 "$ROOT/tools/write_runtime_manifest.py" --profile static "${MANIFEST_ARGUMENTS[@]}" --output "$MANIFEST"
python3 "$ROOT/tools/write_runtime_manifest.py" --profile interop "${MANIFEST_ARGUMENTS[@]}" --output "$INTEROP_MANIFEST"

printf 'umbrella=%s\nstartup=%s\napplication_startup=%s\nharness=%s\ncompute_harness=%s\nchoose_harness=%s\nclassify_harness=%s\ncoalesce_harness=%s\ncoalesce_assign_harness=%s\nstring_length_harness=%s\nobject_alias_harness=%s\nproperty_nullish_assign_harness=%s\nclosure_counter_harness=%s\nclass_counter_harness=%s\nderived_counter_harness=%s\nclass_access_harness=%s\nchecked_object_cast_harness=%s\nmanifest=%s\ninterop_manifest=%s\nsmoke=%s\ngc_smoke=%s\ndynamic_property_smoke=%s\n' "$ARCHIVE" "$STARTUP" "$APPLICATION_STARTUP" "$HARNESS" "$COMPUTE_HARNESS" "$CHOOSE_HARNESS" "$CLASSIFY_HARNESS" "$COALESCE_HARNESS" "$COALESCE_ASSIGN_HARNESS" "$STRING_LENGTH_HARNESS" "$OBJECT_ALIAS_HARNESS" "$PROPERTY_NULLISH_ASSIGN_HARNESS" "$CLOSURE_COUNTER_HARNESS" "$CLASS_COUNTER_HARNESS" "$DERIVED_COUNTER_HARNESS" "$CLASS_ACCESS_HARNESS" "$CHECKED_OBJECT_CAST_HARNESS" "$MANIFEST" "$INTEROP_MANIFEST" "$SMOKE" "$GC_SMOKE" "$DYNAMIC_PROPERTY_SMOKE"
